src/objects/Chinese_Term__c.object
<CustomObject>
    <fields>
        <fullName>Character__c</fullName>
        <label>Character</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>English__c</fullName>
        <label>English</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Session_Date__c</fullName>
        <label>First Session Date</label>
        <summarizedField>Flashcard__c.Completed_Date__c</summarizedField>
        <summaryForeignKey>Flashcard__c.Chinese_Term__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Guest_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Guest Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Session_Date__c</fullName>
        <label>Last Session Date</label>
        <summarizedField>Flashcard__c.Completed_Date__c</summarizedField>
        <summaryForeignKey>Flashcard__c.Chinese_Term__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percent_Correct__c</fullName>
        <formula>Total_Number_Correct__c / Total_Number_of_Sessions__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percent Correct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percent_Incorrect__c</fullName>
        <formula>Total_Number_Incorrect__c / Total_Number_of_Sessions__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percent Incorrect</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pin_Yin__c</fullName>
        <label>Pin Yin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Level__c</fullName>
        <label>Previous Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sound_Link__c</fullName>
        <label>Sound Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Total_Number_Correct__c</fullName>
        <label>Total Number Correct</label>
        <summaryFilterItems>
            <field>Flashcard__c.Number_of_Times_Incorrect__c</field>
            <operation>equals</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Flashcard__c.Completed_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Flashcard__c.Chinese_Term__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Number_Incorrect__c</fullName>
        <label>Total Number Incorrect</label>
        <summaryFilterItems>
            <field>Flashcard__c.Number_of_Times_Incorrect__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Flashcard__c.Completed_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Flashcard__c.Chinese_Term__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Number_of_Sessions__c</fullName>
        <label>Total Number of Sessions</label>
        <summaryFilterItems>
            <field>Flashcard__c.Completed_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Flashcard__c.Chinese_Term__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Chinese Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Chinese Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chinese Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flashcard__c.object
<CustomObject>
    <fields>
        <fullName>Chinese_Term__c</fullName>
        <label>Chinese Term</label>
        <referenceTo>Chinese_Term__c</referenceTo>
        <relationshipLabel>Flashcards</relationshipLabel>
        <relationshipName>Flashcards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Level__c</fullName>
        <label>New Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <label>Flashcard</label>
    <nameField>
        <displayFormat>FL-{0000000}</displayFormat>
        <label>Flashcard Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flashcards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

src/classes/ChineseTermController.cls
public without sharing class ChineseTermController {
    @AuraEnabled
    public static Boolean isCommunity() {
        Id siteId = Site.getSiteId();
        if (siteId != null) {
            return true;
        }
        return false;
    }

    @AuraEnabled
    public static Wrappers.Term getThisTerm(String termId) {
        if (String.isNotBlank(termId)) {
            List<Chinese_Term__c> termList = [SELECT Id, Name, Character__c, Pin_Yin__c, English__c, CreatedDate, Sound_Link__c, Level__c,
                                                    Last_Session_Date__c, Percent_Correct__c, Percent_Incorrect__c, Previous_Level__c,
                                                    Total_Number_Correct__c, Total_Number_Incorrect__c, Total_Number_of_Sessions__c, 
                                                    Is_Active__c, First_Session_Date__c
                                                FROM Chinese_Term__c
                                                WHERE Id =: termId];

            if (!termList.isEmpty()) {
                return new Wrappers.Term(termList[0]);
            }         
        }

        return null;
    }

    @AuraEnabled
    public static List<Wrappers.CardLevel> getTermFlashcards(String termId) {
        List<Wrappers.CardLevel> cardWrapList = new List<Wrappers.CardLevel>();

        if (String.isNotBlank(termId)) {
            List<Chinese_Term__c> termList = [SELECT Id, CreatedDate,
                                                (SELECT Id, New_Level__c, Completed_Date__c
                                                FROM Flashcards__r
                                                WHERE Completed_Date__c != null
                                                AND New_Level__c != null
                                                ORDER BY Completed_Date__c ASC)
                                              FROM Chinese_Term__c
                                              WHERE Id =: termId];

            if (!termList.isEmpty()) {
                Chinese_Term__c thisTerm = termList[0];
                cardWrapList.add(
                    new Wrappers.CardLevel('1', Date.valueOf(thisTerm.CreatedDate))
                );

                for (Flashcard__c card : thisTerm.Flashcards__r) {
                    cardWrapList.add(
                        new Wrappers.CardLevel(card.New_Level__c, card.Completed_Date__c)
                    );
                }
            }
            
        }

        return cardWrapList;
    }

    @AuraEnabled
    public static List<Wrappers.Level> getMyTermLevels(Boolean isGuest, Boolean onlyActive) {
        List<Wrappers.Level> wrapList = new List<Wrappers.Level>();

        String query = 'SELECT Level__c, COUNT(Id) total ';
        query += 'FROM Chinese_Term__c WHERE ';

        if (isGuest) {
            query += 'Guest_Owned__c = true';
        } else {
            query += 'OwnerId = \'' + UserInfo.getUserId() + '\'';
        }

        if (onlyActive) {
            query += ' AND Level__c != \'8\'';
        }

        query += ' GROUP BY Level__c ';
        query += 'ORDER BY Level__c ASC';

        AggregateResult[] groupedResults = Database.query(query);
        Map<String, Integer> levelAmtMap = new Map<String, Integer>();

        for (AggregateResult ar : groupedResults)  {
            String level = (String)ar.get('Level__c');
            Integer total = (Integer)ar.get('total');
            levelAmtMap.put(level, total);
        }

        Integer numLevels = 8;
        if (onlyActive) {
            numLevels = 7;
        }

        for (Integer i = 1; i <= numLevels; i++) {
            String level = String.valueOf(i);
            Integer total = 0;
            if (levelAmtMap.containsKey(level)) {
                total = levelAmtMap.get(level);
            }
            wrapList.add(new Wrappers.Level(level, total));
        }

        return wrapList;
    }

    @AuraEnabled
    public static List<Wrappers.Term> getMyTerms(Boolean isGuest) {
        List<Wrappers.Term> wrapList = new List<Wrappers.Term>();

        String query = 'SELECT Id, Name, Character__c, Pin_Yin__c, English__c, CreatedDate, Sound_Link__c, Level__c, ';
        query += 'Last_Session_Date__c, Percent_Correct__c, Percent_Incorrect__c, Previous_Level__c, Total_Number_Correct__c, ';
        query += 'Total_Number_Incorrect__c, Total_Number_of_Sessions__c, Is_Active__c, First_Session_Date__c ';
        query += 'FROM Chinese_Term__c WHERE ';

        if (isGuest) {
            query += 'Guest_Owned__c = true';
        } else {
            query += 'OwnerId = \'' + UserInfo.getUserId() + '\'';
        }

        query += ' ORDER BY CreatedDate DESC';

        List<Chinese_Term__c> termList = Database.query(query);

        for (Chinese_Term__c term : termList) {
            wrapList.add(new Wrappers.Term(term));
        }

        return wrapList;
    }

    @AuraEnabled
    public static Wrappers.Term saveTerm(String termString, Boolean isGuest) {
        Wrappers.Term termWrap = (Wrappers.Term)JSON.deserialize(termString, Wrappers.Term.class);

        Chinese_Term__c term = new Chinese_Term__c();
        term.Character__c = termWrap.character;
        term.Pin_Yin__c = termWrap.pinYin;
        term.English__c = termWrap.english;

        if (String.isNotBlank(termWrap.termId)) {
            term.Id = termWrap.termId;
            term.Is_Active__c = termWrap.isActive;
        }

        if (isGuest) {
            term.Guest_Owned__c = true;
        }

        try {
            upsert term;

            termWrap.termId = term.Id;
            return termWrap;
        } catch (Exception ex) {
            throw new AuraException(ex.getMessage() + ', Line ' + ex.getLineNumber());
        }
    }

    @AuraEnabled
    public static void saveAttachment(String termId, String fileName, String base64Data) {
        ContentVersion contentInsert = new ContentVersion(); 
        contentInsert.Title = fileName; 
        contentInsert.VersionData = EncodingUtil.base64Decode(base64Data);
        contentInsert.PathOnClient = '/' + fileName ;
        try {
            insert contentInsert;
        } catch (Exception ex) {
            throw new AuraException(ex.getMessage() + ', Line ' + ex.getLineNumber());
        }
        
        contentInsert = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: contentInsert.Id];
        ContentDocumentLink contentLink = new ContentDocumentLink();
        contentLink.ContentDocumentId = contentInsert.ContentDocumentId;
        contentLink.LinkedEntityId = Id.valueOf(termId);
        contentLink.ShareType = 'V';
        contentLink.Visibility = 'AllUsers';
        try {
            insert contentLink;
        } catch (Exception ex) {
            throw new AuraException(ex.getMessage() + ', Line ' + ex.getLineNumber());
        }

        Chinese_Term__c term = new Chinese_Term__c();
        term.Id = Id.valueOf(termId);
        term.Sound_Link__c = '/sfc/servlet.shepherd/version/download/' + contentInsert.Id + '?asPdf=false&operationContext=CHATTER';
        try {
            update term;
        } catch (Exception ex) {
            throw new AuraException(ex.getMessage() + ', Line ' + ex.getLineNumber());
        }
    }
}