src/objects/Chinese_Term__c.object
<CustomObject>
    <fields>
        <fullName>Character__c</fullName>
        <label>Character</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>English__c</fullName>
        <label>English</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guest_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Guest Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pin_Yin__c</fullName>
        <label>Pin Yin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Chinese Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Chinese Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chinese Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deck_Session_Number__c</fullName>
        <label>Deck Session Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Guest_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Guest Owned</label>
        <type>Checkbox</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>SS-{000000000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SessionControllerTest.cls
@isTest
private class SessionControllerTest {
    @isTest
    static void mainTest() {
        Boolean isGuest = false;
        runTest(isGuest);
    }

    @isTest
    static void guestTest() {
        List<User> userList = [SELECT Id, UserType 
                                FROM User 
                                WHERE Profile.Name LIKE 'Chinese Flashcards%' 
                                AND UserType = 'Guest'];

        System.runAs(userList[0]) {
            Boolean isGuest = true;
            runTest(isGuest);
        }
    }

    static void runTest(Boolean isGuest) {
        Session__c sess = new Session__c();
        sess.Deck_Session_Number__c = 1;
        sess.Completed_Date__c = System.today().addDays(-1);
        insert sess;

        List<Chinese_Term__c> terms = new List<Chinese_Term__c>();

        for (Integer i = 0; i < 20; i++) {
            Chinese_Term__c term = new Chinese_Term__c();
            term.Character__c = 'Character' + i;
            term.Pin_Yin__c = 'PinYin' + i;
            term.English__c = 'English' + i;
            term.Guest_Owned__c = isGuest;
            terms.add(term);
        }

        insert terms;

        Test.startTest();

        List<Integer> testNumbers = new List<Integer>{1,6,12,24,32,65};
        for (Integer num : testNumbers) {
            SessionController.getSessionLevels(num);
        }

        String sessionId = SessionController.createSession('Character', terms.size(), isGuest);
        Wrappers.Session sessWrap = SessionController.getFlashcards(sessionId);

        List<Wrappers.Session> sessList = SessionController.getMySessions();
        List<Wrappers.Level> levels = SessionController.getTotalCards(isGuest);

        SessionController.endSession(JSON.serialize(sessWrap));
        SessionController.deleteSession(sessionId);

        Test.stopTest();
    }
}