src/objects/Chinese_Term__c.object
<CustomObject>
    <fields>
        <fullName>Character__c</fullName>
        <label>Character</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>English__c</fullName>
        <label>English</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guest_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Guest Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pin_Yin__c</fullName>
        <label>Pin Yin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Chinese Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Chinese Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chinese Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Deck_Front__c</fullName>
        <label>Deck Front</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Deck_Front</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deck_Session_Number__c</fullName>
        <label>Deck Session Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Guest_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Guest Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Levels__c</fullName>
        <label>Levels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Cards_Drawn__c</fullName>
        <label>Number of New Cards Drawn</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>SS-{000000000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Deck_Front.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Character</fullName>
    </customValue>
    <customValue>
        <fullName>Pin Yin</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Sound</fullName>
    </customValue>
    <masterLabel>Deck Front</masterLabel>
</GlobalValueSet>

src/globalValueSets/Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

src/classes/TRIG_SessionHandlerTest.cls
@isTest
private class TRIG_SessionHandlerTest {
    @isTest
    static void mainTest() {
        Boolean isGuest = false;
        runTest(isGuest);
    }

    @isTest
    static void guestTest() {
        List<User> userList = [SELECT Id, UserType 
                                FROM User 
                                WHERE Profile.Name LIKE 'Chinese Flashcards%' 
                                AND UserType = 'Guest'];

        System.runAs(userList[0]) {
            Boolean isGuest = true;
            runTest(isGuest);
        }
    }

    static void runTest(Boolean isGuest) {
        List<Chinese_Term__c> terms = new List<Chinese_Term__c>();

        for (Integer i = 0; i < 20; i++) {
            Chinese_Term__c term = new Chinese_Term__c();
            term.Character__c = 'Character' + i;
            term.Pin_Yin__c = 'PinYin' + i;
            term.English__c = 'English' + i;
            term.Guest_Owned__c = isGuest;
            terms.add(term);
        }

        insert terms;

        Test.startTest();

        Session__c sess = new Session__c();
        sess.Deck_Front__c = 'Character';
        sess.Number_of_Cards_Drawn__c = 10;
        sess.Deck_Session_Number__c = 1;
        sess.Levels__c = '1';
        sess.Guest_Owned__c = isGuest;
        insert sess;

        Test.stopTest();
    }
}