src/objects/Chinese_Term__c.object
<CustomObject>
    <fields>
        <fullName>Character__c</fullName>
        <label>Character</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>English__c</fullName>
        <label>English</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Session_Date__c</fullName>
        <label>First Session Date</label>
        <summarizedField>Flashcard__c.Completed_Date__c</summarizedField>
        <summaryForeignKey>Flashcard__c.Chinese_Term__c</summaryForeignKey>
        <summaryOperation>min</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Session_Date__c</fullName>
        <label>Last Session Date</label>
        <summarizedField>Flashcard__c.Completed_Date__c</summarizedField>
        <summaryForeignKey>Flashcard__c.Chinese_Term__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Percent_Correct__c</fullName>
        <formula>Total_Number_Correct__c / Total_Number_of_Sessions__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percent Correct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percent_Incorrect__c</fullName>
        <formula>Total_Number_Incorrect__c / Total_Number_of_Sessions__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percent Incorrect</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pin_Yin__c</fullName>
        <label>Pin Yin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Level__c</fullName>
        <label>Previous Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sound_Link__c</fullName>
        <label>Sound Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Total_Number_Correct__c</fullName>
        <label>Total Number Correct</label>
        <summaryFilterItems>
            <field>Flashcard__c.Number_of_Times_Incorrect__c</field>
            <operation>equals</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Flashcard__c.Completed_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Flashcard__c.Chinese_Term__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Number_Incorrect__c</fullName>
        <label>Total Number Incorrect</label>
        <summaryFilterItems>
            <field>Flashcard__c.Number_of_Times_Incorrect__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Flashcard__c.Completed_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Flashcard__c.Chinese_Term__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Number_of_Sessions__c</fullName>
        <label>Total Number of Sessions</label>
        <summaryFilterItems>
            <field>Flashcard__c.Completed_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Flashcard__c.Chinese_Term__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Chinese Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Chinese Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chinese Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flashcard__c.object
<CustomObject>
    <fields>
        <fullName>Chinese_Term__c</fullName>
        <label>Chinese Term</label>
        <referenceTo>Chinese_Term__c</referenceTo>
        <relationshipLabel>Flashcards</relationshipLabel>
        <relationshipName>Flashcards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Level__c</fullName>
        <label>New Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Times_Incorrect__c</fullName>
        <label>Number of Times Incorrect</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Original_Level__c</fullName>
        <label>Original Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Flashcards</relationshipLabel>
        <relationshipName>Flashcards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Flashcard</label>
    <nameField>
        <displayFormat>FL-{0000000}</displayFormat>
        <label>Flashcard Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flashcards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deck_Front__c</fullName>
        <label>Deck Front</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Deck_Front</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Levels__c</fullName>
        <label>Levels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Cards_Drawn__c</fullName>
        <label>Number of New Cards Drawn</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percent_Correct__c</fullName>
        <formula>Total_Number_Correct__c / Total_Number_of_Cards__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percent Correct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percent_Incorrect__c</fullName>
        <formula>Total_Number_Incorrect__c / Total_Number_of_Cards__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percent Incorrect</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Number_Correct__c</fullName>
        <label>Total Number Correct</label>
        <summaryFilterItems>
            <field>Flashcard__c.Number_of_Times_Incorrect__c</field>
            <operation>equals</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Flashcard__c.Session__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Number_Incorrect__c</fullName>
        <label>Total Number Incorrect</label>
        <summaryFilterItems>
            <field>Flashcard__c.Number_of_Times_Incorrect__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Flashcard__c.Session__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Number_of_Cards__c</fullName>
        <label>Total Number of Cards</label>
        <summaryForeignKey>Flashcard__c.Session__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>SS-{000000000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Deck_Front.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Character</fullName>
    </customValue>
    <customValue>
        <fullName>Pin Yin</fullName>
    </customValue>
    <customValue>
        <fullName>English</fullName>
    </customValue>
    <customValue>
        <fullName>Sound</fullName>
    </customValue>
    <masterLabel>Deck Front</masterLabel>
</GlobalValueSet>

src/globalValueSets/Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

src/classes/Wrappers.cls
public without sharing class Wrappers {
    public class Level {
        @AuraEnabled
        public String level {get;set;}
        @AuraEnabled
        public Integer amount {get;set;}

        public Level(String level, Integer amount) {
            this.level = level;
            this.amount = amount;
        }
    }

    public class CardLevel {
        @AuraEnabled
        public Integer level {get;set;}
        @AuraEnabled
        public String completedDate {get;set;}

        public CardLevel(String newLevel, Date compDate) {
            this.level = Integer.valueOf(newLevel);

            Datetime compDateTime = Datetime.newInstance(compDate.year(), compDate.month(), compDate.day());
            this.completedDate = compDateTime.format('M/d/y');
        }
    }
    
    public class Session {
        @AuraEnabled
        public String sessId {get;set;}
        @AuraEnabled
        public String sessLink {get;set;}
        @AuraEnabled
        public String name {get;set;}
        @AuraEnabled
        public String deckFront {get;set;}
        @AuraEnabled
        public String levels {get;set;}
        @AuraEnabled
        public Integer numDrawn {get;set;}
        @AuraEnabled
        public Date completedDate {get;set;}
        @AuraEnabled
        public Integer totalCards {get;set;}
        @AuraEnabled
        public Integer correctCards {get;set;}
        @AuraEnabled
        public Integer incorrectCards {get;set;}
        @AuraEnabled
        public List<Flashcard> flashcards {get;set;}

        public Session(Session__c sess, List<Flashcard> flashcards) {
            this.sessId = sess.Id;
            this.sessLink = '/' + sess.Id;
            this.name = sess.Name;
            this.deckFront = sess.Deck_Front__c;
            this.numDrawn = Integer.valueOf(sess.Number_of_Cards_Drawn__c);
            this.flashcards = flashcards;

            if (String.isNotBlank(sess.Levels__c)) {
                this.levels = String.join(sess.Levels__c.split(';'), ', ');
            }

            if (sess.Completed_Date__c != null && sess.Total_Number_of_Cards__c > 0) {
                this.completedDate = sess.Completed_Date__c;
                this.totalCards = Integer.valueOf(sess.Total_Number_of_Cards__c);
                this.correctCards = Integer.valueOf(sess.Total_Number_Correct__c);
                this.incorrectCards = Integer.valueOf(sess.Total_Number_Incorrect__c);
            } else {
                this.completedDate = null;
                this.totalCards = 0;
                this.correctCards = 0;
                this.incorrectCards = 0;
            }
        }
    }

    public class Flashcard {
        @AuraEnabled
        public String cardId {get;set;}
        @AuraEnabled
        public String deckFront {get;set;}
        @AuraEnabled
        public Integer numIncorrect {get;set;}
        @AuraEnabled
        public String levelChange {get;set;}
        @AuraEnabled
        public Term term {get;set;}

        public Flashcard(Flashcard__c card, String deckFront) {
            this.cardId = card.Id;
            this.deckFront = deckFront;
            this.term = new Term(card.Chinese_Term__r);

            if (card.Number_of_Times_Incorrect__c != null && card.Number_of_Times_Incorrect__c > 0) {
                this.numIncorrect = Integer.valueOf(card.Number_of_Times_Incorrect__c);
            } else {
                this.numIncorrect = 0;
            }

            if (String.isNotBlank(card.Original_Level__c) && String.isNotBlank(card.New_Level__c)) {
                this.levelChange = card.Original_Level__c + ' → ' + card.New_Level__c;
            }
        }
    }

    public class Term {
        @AuraEnabled
        public String termId {get;set;}
        @AuraEnabled
        public String termLink {get;set;}
        @AuraEnabled
        public String name {get;set;}
        @AuraEnabled
        public String character {get;set;}
        @AuraEnabled
        public String pinYin {get;set;}
        @AuraEnabled
        public String english {get;set;}
        @AuraEnabled
        public String sound {get;set;}
        @AuraEnabled
        public String level {get;set;}
        @AuraEnabled
        public String prevLevel {get;set;}
        @AuraEnabled
        public Date createdDate {get;set;}
        @AuraEnabled
        public Date firstSessionDate {get;set;}
        @AuraEnabled
        public Date lastSessionDate {get;set;}
        @AuraEnabled
        public Integer numSessions {get;set;}
        @AuraEnabled
        public Integer numCorrect {get;set;}
        @AuraEnabled
        public Integer numIncorrect {get;set;}
        @AuraEnabled
        public Decimal pctCorrect {get;set;}
        @AuraEnabled
        public Decimal pctIncorrect {get;set;}
        @AuraEnabled
        public Boolean isActive {get;set;}

        public Term(Chinese_Term__c term) {
            this.termId = term.Id;
            this.termLink = '/' + term.Id;
            this.name = term.Name;
            this.character = term.Character__c;
            this.pinYin = term.Pin_Yin__c;
            this.english = term.English__c;
            this.sound = term.Sound_Link__c;
            this.level = term.Level__c;
            this.prevLevel = term.Previous_Level__c;
            this.isActive = term.Is_Active__c;

            Datetime dt = term.CreatedDate;
            this.createdDate = Date.newInstance(dt.year(), dt.month(), dt.day());

            if (term.Total_Number_of_Sessions__c > 0) {
                this.firstSessionDate = term.First_Session_Date__c;
                this.lastSessionDate = term.Last_Session_Date__c;
                this.numSessions = Integer.valueOf(term.Total_Number_of_Sessions__c);
                this.numCorrect = Integer.valueOf(term.Total_Number_Correct__c);
                this.numIncorrect = Integer.valueOf(term.Total_Number_Incorrect__c);
                this.pctCorrect = term.Percent_Correct__c / 100;
                this.pctIncorrect = term.Percent_Incorrect__c / 100;
            } else {
                this.firstSessionDate = null;
                this.lastSessionDate = null;
                this.numSessions = 0;
                this.numCorrect = 0;
                this.numIncorrect = 0;
                this.pctCorrect = 0;
                this.pctIncorrect = 0;
            }
        }
    }
}