src/objects/Chinese_Term__c.object
<CustomObject>
    <fields>
        <fullName>Character__c</fullName>
        <label>Character</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>English__c</fullName>
        <label>English</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guest_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Guest Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pin_Yin__c</fullName>
        <label>Pin Yin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Chinese Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Chinese Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chinese Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flashcard__c.object
<CustomObject>
    <fields>
        <fullName>Chinese_Term__c</fullName>
        <label>Chinese Term</label>
        <referenceTo>Chinese_Term__c</referenceTo>
        <relationshipLabel>Flashcards</relationshipLabel>
        <relationshipName>Flashcards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Level__c</fullName>
        <label>New Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Times_Incorrect__c</fullName>
        <label>Number of Times Incorrect</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Original_Level__c</fullName>
        <label>Original Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Flashcards</relationshipLabel>
        <relationshipName>Flashcards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Flashcard</label>
    <nameField>
        <displayFormat>FL-{0000000}</displayFormat>
        <label>Flashcard Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flashcards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deck_Session_Number__c</fullName>
        <label>Deck Session Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Guest_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Guest Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Levels__c</fullName>
        <label>Levels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Cards_Drawn__c</fullName>
        <label>Number of New Cards Drawn</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>SS-{000000000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

src/classes/ChineseTermControllerTest.cls
@isTest
private class ChineseTermControllerTest {
    @isTest
    static void mainTest() {
        Boolean isGuest = false;
        runTest(isGuest);
    }

    @isTest
    static void guestTest() {
        Boolean isGuest = true;
        runTest(isGuest);
    }

    static void runTest(Boolean isGuest) {
        Chinese_Term__c term = new Chinese_Term__c();
        term.Character__c = 'Character';
        term.Pin_Yin__c = 'PinYin';
        term.English__c = 'English';
        term.Guest_Owned__c = isGuest;
        insert term;

        Session__c sess = new Session__c();
        sess.Deck_Session_Number__c = 1;
        sess.Number_of_Cards_Drawn__c = 1;
        sess.Levels__c = '1';
        sess.Completed_Date__c = System.today();
        insert sess;

        List<Flashcard__c> cardList = [SELECT Id FROM Flashcard__c];
        for (Flashcard__c card : cardList) {
            card.Number_of_Times_Incorrect__c = 0;
            card.Original_Level__c = '1';
            card.New_Level__c = '2';
            card.Completed_Date__c = System.today();
        }
        update cardList;

        Test.startTest();

        Boolean isComm = ChineseTermController.isCommunity();
        List<Wrappers.Term> termWrapList = ChineseTermController.getMyTerms(isGuest);

        Wrappers.Term thisTerm = ChineseTermController.getThisTerm(term.Id);
        Wrappers.Term savedTerm = ChineseTermController.saveTerm(JSON.serialize(thisTerm), isGuest);

        List<Wrappers.CardLevel> cardLevelList = ChineseTermController.getTermFlashcards(term.Id);
        List<Wrappers.Level> levelList = ChineseTermController.getMyTermLevels(isGuest, true);

        String fileData = EncodingUtil.base64Encode(Blob.valueOf('This is a test sound file upload!'));
        ChineseTermController.saveAttachment(termWrapList[0].termId, 'audio.mp3', fileData);

        Test.stopTest();
    }
}