src/objects/Chinese_Term__c.object
<CustomObject>
    <fields>
        <fullName>Guest_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Guest Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Session_Date__c</fullName>
        <label>Last Session Date</label>
        <summarizedField>Flashcard__c.Completed_Date__c</summarizedField>
        <summaryForeignKey>Flashcard__c.Chinese_Term__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <label>Chinese Term</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Chinese Term Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chinese Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flashcard__c.object
<CustomObject>
    <fields>
        <fullName>Chinese_Term__c</fullName>
        <label>Chinese Term</label>
        <referenceTo>Chinese_Term__c</referenceTo>
        <relationshipLabel>Flashcards</relationshipLabel>
        <relationshipName>Flashcards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Flashcards</relationshipLabel>
        <relationshipName>Flashcards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Flashcard</label>
    <nameField>
        <displayFormat>FL-{0000000}</displayFormat>
        <label>Flashcard Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flashcards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Guest_Owned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Guest Owned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Levels__c</fullName>
        <label>Levels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Level</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Cards_Drawn__c</fullName>
        <label>Number of New Cards Drawn</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>SS-{000000000}</displayFormat>
        <label>Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Level.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>2</fullName>
    </customValue>
    <customValue>
        <fullName>3</fullName>
    </customValue>
    <customValue>
        <fullName>4</fullName>
    </customValue>
    <customValue>
        <fullName>5</fullName>
    </customValue>
    <customValue>
        <fullName>6</fullName>
    </customValue>
    <customValue>
        <fullName>7</fullName>
    </customValue>
    <customValue>
        <fullName>8</fullName>
    </customValue>
    <masterLabel>Level</masterLabel>
</GlobalValueSet>

src/classes/TRIG_SessionHandler.cls
public without sharing class TRIG_SessionHandler {
    public static void afterInsert(List<Session__c> triggerNew) {
        Set<String> levels = new Set<String>();
        Set<Id> ownerIds = new Set<Id>();

        for (Session__c sess : triggerNew) {
            if (String.isNotBlank(sess.Levels__c)) {
                List<String> allLevelsList = sess.Levels__c.split(';');
                levels.addAll(allLevelsList);
            }

            ownerIds.add(sess.CreatedById);
        }

        if (!levels.isEmpty() && !ownerIds.isEmpty()) {
            List<User> guestList = [SELECT Id 
                                    FROM User 
                                    WHERE Profile.Name LIKE 'Chinese Flashcards%' 
                                    AND UserType = 'Guest'];

            Id guestId;
            if (!guestList.isEmpty()) {
                if (ownerIds.contains(guestList[0].Id)) {
                    guestId = guestList[0].Id;
                }
            }

            String query = 'SELECT Id, Level__c, OwnerId, Guest_Owned__c ';
            query += 'FROM Chinese_Term__c ';
            query += 'WHERE Is_Active__c = true AND Level__c IN :levels ';
            query += 'AND (Last_Session_Date__c = null OR Last_Session_Date__c < TODAY) ';

            if (guestId != null) {
                query += 'AND (Guest_Owned__c = true OR OwnerId IN :ownerIds)';
            } else {
                query += 'AND OwnerId IN :ownerIds';
            }

            query += ' ORDER BY Level__c DESC NULLS LAST, CreatedDate ASC';

            List<Chinese_Term__c> termList = Database.query(query);

            Map<Id, Map<String, List<Chinese_Term__c>>> levelTermMap = new Map<Id, Map<String, List<Chinese_Term__c>>>();

            for (Chinese_Term__c term : termList) {
                Id userId;
                if (term.Guest_Owned__c) {
                    userId = guestId;
                } else {
                    userId = term.OwnerId;
                }

                if (levelTermMap.containsKey(userId)) {
                    Map<String, List<Chinese_Term__c>> levelMap = levelTermMap.get(userId);

                    if (levelMap.containsKey(term.Level__c)) {
                        levelMap.get(term.Level__c).add(term);
                    } else {
                        levelMap.put(term.Level__c, new List<Chinese_Term__c>{term});
                    }

                    levelTermMap.put(userId, levelMap);
                } else {
                    Map<String, List<Chinese_Term__c>> levelMap = new Map<String, List<Chinese_Term__c>>{term.Level__c => new List<Chinese_Term__c>{term}};
                    levelTermMap.put(userId, levelMap);
                }
            }

            List<Flashcard__c> cardsToInsert = new List<Flashcard__c>();

            for (Session__c sess : triggerNew) {
                if (levelTermMap.containsKey(sess.CreatedById)) {
                    Map<String, List<Chinese_Term__c>> levelMap = levelTermMap.get(sess.CreatedById);
                    List<String> allLevelsList = sess.Levels__c.split(';');

                    for (String level : allLevelsList) {
                        if (levelMap.containsKey(level)) {
                            List<Chinese_Term__c> terms = levelMap.get(level);

                            for (Integer i = 0; i < terms.size(); i++) {
                                if (sess.Number_of_Cards_Drawn__c < (i + 1)
                                        && level == '1') {
                                    break;
                                }

                                Flashcard__c card = new Flashcard__c();
                                card.Session__c = sess.Id;
                                card.Chinese_Term__c = terms[i].Id;
                                cardsToInsert.add(card);
                            }
                        }
                    }
                }
            }

            if (!cardsToInsert.isEmpty()) {
                insert cardsToInsert;
            }
        }
    }
}